In [30]:
import torch
# 不带out参数类型
a = torch.tensor([[True, False, True], [True, False, True]])
b = torch.tensor([[False, False, False], [True, False, True]])
print(torch.logical_and(a, b))

tensor([[False, False, False],
        [ True, False,  True]])


In [31]:
x = torch.tensor([[1,2,3], [4, 5, 6]])
print(x)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [32]:
k = torch.logical_and(a, b)
x = x[k]
print(x)

tensor([4, 6])


In [33]:
k1 = k.bool()
print(k1)

tensor([[False, False, False],
        [ True, False,  True]])


In [34]:
x1 = x.bool()
print(x1)

tensor([True, True])


In [36]:
T1 = torch.tensor([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
 # 假设是时间步T2
T2 = torch.tensor([[10, 20, 30],
                 [40, 50, 60]])

print(torch.stack((T1,T2)).shape)

RuntimeError: stack expects each tensor to be equal size, but got [3, 3] at entry 0 and [2, 3] at entry 1

In [40]:
import torch
import numpy as np
 
class Dataset(torch.utils.data.Dataset):
    def __init__(self):
        self.data = [i for i in range(40)]
        print(111)
 
    def __len__(self):
        return len(self.data)
 
    def __getitem__(self, idx):
        print(self.worker_id, id(self.data))
        tensor = torch.FloatTensor([self.data[idx]])
        return tensor
 
    def worker_init_fn(self, worker_id):
        print(worker_id)
        self.worker_id = worker_id
        self.data = [i for i in range(40)]
 
if __name__ == '__main__':
    dataset = Dataset()
    dataloader = torch.utils.data.DataLoader(
            dataset=dataset,
            shuffle=True,
            batch_size=20,
            num_workers=4,
            worker_init_fn=dataset.worker_init_fn)
 
    for idx, d in enumerate(dataloader):
        print(idx, d.shape)

111
0213



01  140504047878528140504047577280

01  140504047878528140504047577280

01  140504047878528140504047577280

01  140504047577280140504047878528

10  140504047577280140504047878528

10  140504047577280140504047878528

10  140504047577280140504047878528

10  140504047577280140504047878528

10  140504047577280140504047878528

10  140504047577280140504047878528

10  140504047577280140504047878528

10  140504047577280140504047878528

10  140504047878528140504047577280

10  140504047577280140504047878528

1 0140504047577280 
1405040478785281 
1405040475772800
 1140504047878528 
1405040475772800
 1140504047878528 
1405040475772800
 1140504047878528 
140504047577280
01  140504047878528140504047577280

0 140504047878528
0 torch.Size([20, 1])
1 torch.Size([20, 1])
